[rospy.client][INFO] 2021-12-08 10:40:28,712: init_node, name[/server_endpoint], pid[1290]
[xmlrpc][INFO] 2021-12-08 10:40:28,712: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-08 10:40:28,712: Started XML-RPC server [http://wng:38267/]
[rospy.init][INFO] 2021-12-08 10:40:28,712: ROS Slave URI: [http://wng:38267/]
[rospy.impl.masterslave][INFO] 2021-12-08 10:40:28,712: _ready: http://wng:38267/
[rospy.registration][INFO] 2021-12-08 10:40:28,713: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-12-08 10:40:28,713: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-08 10:40:28,813: registered with master
[rospy.rosout][INFO] 2021-12-08 10:40:28,813: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-08 10:40:28,814: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-08 10:40:28,814: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-08 10:40:28,821: Starting server on 125.129.64.66:10000
[rospy.internal][INFO] 2021-12-08 10:40:29,090: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-08 10:40:32,773: Connection from 125.129.64.66
[rosout][INFO] 2021-12-08 10:40:32,778: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-08 10:40:32,829: topic[/execution_check] adding connection to [http://wng:38267/], count 0
[rospy.internal][INFO] 2021-12-08 10:40:32,831: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-08 10:52:21,895: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-08 10:52:21,901: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-08 10:52:21,901: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-08 10:52:21,901: topic[/execution_check] removing connection to http://wng:38267/
[rospy.impl.masterslave][INFO] 2021-12-08 10:52:21,902: signal-2
[rospy.internal][WARNING] 2021-12-08 10:52:21,902: Unknown error initiating TCP/IP socket to wng:42241 (http://wng:38267/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2021-12-08 10:52:22,066: signal_shutdown [atexit]
