[rospy.client][INFO] 2021-12-14 10:44:07,322: init_node, name[/server_endpoint], pid[20280]
[xmlrpc][INFO] 2021-12-14 10:44:07,322: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-14 10:44:07,322: Started XML-RPC server [http://wng:39883/]
[rospy.init][INFO] 2021-12-14 10:44:07,323: ROS Slave URI: [http://wng:39883/]
[rospy.impl.masterslave][INFO] 2021-12-14 10:44:07,323: _ready: http://wng:39883/
[xmlrpc][INFO] 2021-12-14 10:44:07,323: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-14 10:44:07,323: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-12-14 10:44:07,423: registered with master
[rospy.rosout][INFO] 2021-12-14 10:44:07,423: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-14 10:44:07,424: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-14 10:44:07,425: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-14 10:44:07,430: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-14 10:44:07,657: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-14 10:44:16,491: Connection from 192.168.0.8
[rosout][INFO] 2021-12-14 10:44:16,496: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-14 10:44:16,604: topic[/execution_check] adding connection to [http://wng:39883/], count 0
[rospy.internal][INFO] 2021-12-14 10:44:16,606: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rospy.core][INFO] 2021-12-14 10:45:38,115: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-14 10:45:38,125: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-14 10:45:38,126: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-14 10:45:38,126: topic[/execution_check] removing connection to http://wng:39883/
[rospy.internal][ERROR] 2021-12-14 10:45:38,126: Unable to initiate TCP/IP socket to wng:34787 (http://wng:39883/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.impl.masterslave][INFO] 2021-12-14 10:45:38,126: signal-2
[rospy.core][INFO] 2021-12-14 10:45:38,227: signal_shutdown [atexit]
