[rospy.client][INFO] 2021-12-14 10:24:15,791: init_node, name[/server_endpoint], pid[16642]
[xmlrpc][INFO] 2021-12-14 10:24:15,792: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-14 10:24:15,792: Started XML-RPC server [http://wng:33847/]
[rospy.init][INFO] 2021-12-14 10:24:15,792: ROS Slave URI: [http://wng:33847/]
[rospy.impl.masterslave][INFO] 2021-12-14 10:24:15,792: _ready: http://wng:33847/
[rospy.registration][INFO] 2021-12-14 10:24:15,793: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2021-12-14 10:24:15,793: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-14 10:24:15,892: registered with master
[rospy.rosout][INFO] 2021-12-14 10:24:15,893: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-14 10:24:15,894: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-14 10:24:15,895: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-14 10:24:15,901: Starting server on 192.168.0.8:10000
[rospy.internal][INFO] 2021-12-14 10:24:16,106: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-12-14 10:25:44,410: Connection from 192.168.0.8
[rosout][INFO] 2021-12-14 10:25:44,415: RegisterPublisher(execution_check, <class 'panda_move.msg._ExecutionCheck.ExecutionCheck'>) OK
[rospy.internal][INFO] 2021-12-14 10:25:44,436: topic[/execution_check] adding connection to [http://wng:33847/], count 0
[rospy.internal][INFO] 2021-12-14 10:25:44,437: topic[/execution_check] adding connection to [/server_endpoint], count 0
[rosout][ERROR] 2021-12-14 10:29:57,746: Exception: No more data available
[rosout][INFO] 2021-12-14 10:29:57,747: Disconnected from 192.168.0.8
[rospy.core][INFO] 2021-12-14 10:30:10,043: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-14 10:30:10,050: topic[/execution_check] removing connection to /server_endpoint
[rospy.internal][INFO] 2021-12-14 10:30:10,051: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-14 10:30:10,051: topic[/execution_check] removing connection to http://wng:33847/
[rospy.internal][ERROR] 2021-12-14 10:30:10,051: Unable to initiate TCP/IP socket to wng:42195 (http://wng:33847/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.impl.masterslave][INFO] 2021-12-14 10:30:10,051: signal-2
[rospy.core][INFO] 2021-12-14 10:30:10,183: signal_shutdown [atexit]
